apiVersion: batch/v1
kind: Job
metadata:
  name: corplist
  namespace: gd
spec:
  template:
    spec:
      containers:
      - name: corplist
        image: docker.io/bluesquanium/corplist
      restartPolicy: OnFailure