apiVersion: batch/v1
kind: Job
metadata:
  name: financial-statement
  namespace: gd
spec:
  template:
    spec:
      containers:
      - name: financial-statement
        image: docker.io/bluesquanium/financial-statement
      restartPolicy: OnFailure
